# Generated by Django 5.2.8 on 2025-12-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_comment_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='commentText',
        ),
    ]
