# Generated by Django 5.2.8 on 2025-12-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_sigma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sigma',
        ),
    ]
