# Generated by Django 5.2.8 on 2025-12-15 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_article_alter_comment_options_comment_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hello.article'),
            preserve_default=False,
        ),
    ]
