# Generated by Django 5.2.8 on 2025-12-15 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_comment_article_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article_id',
            new_name='article',
        ),
    ]
