# Generated by Django 5.2.8 on 2025-12-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_rename_article_id_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='anon', max_length=40, verbose_name='Автор комментария'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='abc@mail.ru', max_length=254, verbose_name='Эл. почта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images', verbose_name='Главное изображение'),
        ),
    ]
