# Generated by Django 5.2.8 on 2026-03-04 12:12

import imagesApp.models
import imagesApp.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "original",
                    models.ImageField(
                        upload_to=imagesApp.models.upload_to,
                        validators=[
                            imagesApp.validators.validate_image,
                            imagesApp.validators.validate_file_size,
                        ],
                    ),
                ),
                ("preview", models.ImageField(blank=True, upload_to="")),
                ("thumb", models.ImageField(blank=True, upload_to="")),
                ("webp", models.ImageField(blank=True, upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
