# Generated by Django 5.2.8 on 2025-12-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_comment_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sigma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'jojo',
                'verbose_name_plural': 'jojos',
            },
        ),
    ]
